docker_management_commands = [
  { tech: 'docker', command: 'builder', usage: 'docker builder [OPTIONS] COMMAND', result: { es: 'Gestiona las construcciones', en: 'Manage builds' }, level: 1, nb: {} },
  { tech: 'docker', command: 'buildx', usage: 'docker buildx [OPTIONS] COMMAND', result: { es: 'Docker Buildx', en: 'Docker Buildx (Docker Inc., v0.9.1)' }, level: 1, nb: {} },
  { tech: 'docker', command: 'compose', usage: 'docker compose [OPTIONS] COMMAND', result: { es: 'Docker Compose', en: 'Docker Compose (Docker Inc., v2.10.2)' }, level: 1, nb: {} },
  { tech: 'docker', command: 'config', usage: 'docker config [OPTIONS] COMMAND', result: { es: 'Gestiona las configuraciones de Docker', en: 'Manage Docker configs' }, level: 1, nb: {} },
  { tech: 'docker', command: 'container', usage: 'docker container [OPTIONS] COMMAND', result: { es: 'Gestiona contenedores', en: 'Manage containers' }, level: 1, nb: {} },
  { tech: 'docker', command: 'context', usage: 'docker context [OPTIONS] COMMAND', result: { es: 'Gestiona los contextos', en: 'Manage contexts' }, level: 1, nb: {} },
  { tech: 'docker', command: 'extension', usage: 'docker extension [OPTIONS] COMMAND', result: { es: 'Gestiona las extensiones de Docker', en: 'Manages Docker extensions (Docker Inc., v0.2.9)' }, level: 1, nb: {} },
  { tech: 'docker', command: 'image', usage: 'docker image [OPTIONS] COMMAND', result: { es: 'Gestiona imágenes', en: 'Manage images' }, level: 1, nb: {} },
  { tech: 'docker', command: 'manifest', usage: 'docker manifest [OPTIONS] COMMAND', result: { es: 'Gestiona las listas de manifiestos y manifiestos de imágenes de Docker', en: 'Manage Docker image manifests and manifest lists' }, level: 1, nb: {} },
  { tech: 'docker', command: 'network', usage: 'docker network [OPTIONS] COMMAND', result: { es: 'Gestiona redes', en: 'Manage networks' }, level: 1, nb: {} },
  { tech: 'docker', command: 'node', usage: 'docker node [OPTIONS] COMMAND', result: { es: 'Gestiona los nodos de Swarm', en: 'Manage Swarm nodes' }, level: 1, nb: {} },
  { tech: 'docker', command: 'plugin', usage: 'docker plugin [OPTIONS] COMMAND', result: { es: 'Gestiona los plugins', en: 'Manage plugins' }, level: 1, nb: {} },
  { tech: 'docker', command: 'sbom', usage: 'docker sbom [OPTIONS] COMMAND', result: { es: 'Ver el Software Bill Of Materials basado en paquetes (SBOM) para una imagen', en: 'View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)' }, level: 1, nb: {} },
  { tech: 'docker', command: 'scan', usage: 'docker scan [OPTIONS] COMMAND', result: { es: 'Docker Scan', en: 'Docker Scan (Docker Inc., v0.19.0)' }, level: 1, nb: {} },
  { tech: 'docker', command: 'secret', usage: 'docker secret [OPTIONS] COMMAND', result: { es: 'Gestiona los secretos de Docker', en: 'Manage Docker secrets' }, level: 1, nb: {} },
  { tech: 'docker', command: 'service', usage: 'docker service [OPTIONS] COMMAND', result: { es: 'Gestiona los servicios', en: 'Manage services' }, level: 1, nb: {} },
  { tech: 'docker', command: 'stack', usage: 'docker stack [OPTIONS] COMMAND', result: { es: 'Gestiona las pilas de Docker', en: 'Manage Docker stacks' }, level: 1, nb: {} },
  { tech: 'docker', command: 'swarm', usage: 'docker swarm [OPTIONS] COMMAND', result: { es: 'Gestiona Swarm', en: 'Manage Swarm' }, level: 1, nb: {} },
  { tech: 'docker', command: 'system', usage: 'docker system [OPTIONS] COMMAND', result: { es: 'Gestiona Docker', en: 'Manage Docker' }, level: 1, nb: {} },
  { tech: 'docker', command: 'trust', usage: 'docker trust [OPTIONS] COMMAND', result: { es: 'Gestiona la confianza en las imágenes de Docker', en: 'Manage trust on Docker images' }, level: 1, nb: {} },
  { tech: 'docker', command: 'volume', usage: 'docker volume [OPTIONS] COMMAND', result: { es: 'Gestiona los volúmenes', en: 'Manage volumes' }, level: 1, nb: {} }
]

docker_commands = [
  { tech: 'docker', command: 'attach', usage: 'docker attach [OPTIONS] CONTAINER', result: { es: 'Adjunta la entrada, salida y errores estándar locales a un contenedor en ejecución', en: 'Attach local standard input, output, and error streams to a running container' }, level: 1, nb: {} },
  { tech: 'docker', command: 'build', usage: 'docker build [OPTIONS] PATH | URL | -', result: { es: 'Construir una imagen a partir de un Dockerfile', en: 'Build an image from a Dockerfile' }, level: 1, nb: {} },
  { tech: 'docker', command: 'commit', usage: 'docker commit [OPTIONS] CONTAINER [REPOSITORY[:TAG]]', result: { es: 'Crear una nueva imagen a partir de los cambios de un contenedor', en: "Create a new image from a container's changes" }, level: 1, nb: {} },
  { tech: 'docker', command: 'cp', usage: 'docker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH|-', result: { es: 'Copiar archivos/carpetas entre un contenedor y el sistema de archivos local', en: 'Copy files/folders between a container and the local filesystem' }, level: 1, nb: {} },
  { tech: 'docker', command: 'create', usage: 'docker create [OPTIONS] IMAGE [COMMAND] [ARG...]', result: { es: 'Crear un nuevo contenedor', en: 'Create a new container' }, level: 1, nb: {} },
  { tech: 'docker', command: 'diff', usage: 'docker diff CONTAINER', result: { es: 'Inspeccionar cambios en archivos o directorios en el sistema de archivos de un contenedor', en: "Inspect changes to files or directories on a container's filesystem" }, level: 1, nb: {} },
  { tech: 'docker', command: 'events', usage: 'docker events [OPTIONS]', result: { es: 'Obtener eventos en tiempo real del servidor', en: 'Get real time events from the server' }, level: 1, nb: {} },
  { tech: 'docker', command: 'exec', usage: 'docker exec [OPTIONS] CONTAINER COMMAND [ARG...]', result: { es: 'Ejecutar un comando en un contenedor en ejecución', en: 'Run a command in a running container' }, level: 1, nb: {} },
  { tech: 'docker', command: 'export', usage: 'docker export [OPTIONS] CONTAINER', result: { es: 'Exportar el sistema de archivos de un contenedor como un archivo tar', en: "Export a container's filesystem as a tar archive" }, level: 1, nb: {} },
  { tech: 'docker', command: 'history', usage: 'docker history [OPTIONS] IMAGE', result: { es: 'Mostrar el historial de una imagen', en: 'Show the history of an image' }, level: 1, nb: {} },
  { tech: 'docker', command: 'images', usage: 'docker images [OPTIONS] [REPOSITORY[:TAG]]', result: { es: 'Listar imágenes', en: 'List images' }, level: 1, nb: {} },
  { tech: 'docker', command: 'import', usage: 'docker import [OPTIONS] file|URL|- [REPOSITORY[:TAG]]', result: { es: 'Importar el contenido de un archivo tar para crear una imagen de sistema de archivos', en: 'Import the contents from a tarball to create a filesystem image' }, level: 1, nb: {} },
  { tech: 'docker', command: 'info', usage: 'docker info [OPTIONS]', result: { es: 'Mostrar información del sistema', en: 'Display system-wide information' }, level: 1, nb: {} },
  { tech: 'docker', command: 'inspect', usage: 'docker inspect [OPTIONS] NAME|ID [NAME|ID...]', result: { es: 'Devolver información de bajo nivel sobre objetos de Docker', en: 'Return low-level information on Docker objects' }, level: 1, nb: {} },
  { tech: 'docker', command: 'kill', usage: 'docker kill [OPTIONS] CONTAINER [CONTAINER...]', result: { es: 'Matar uno o más contenedores en ejecución', en: 'Kill one or more running containers' }, level: 1, nb: {} },
  { tech: 'docker', command: 'load', usage: 'docker load [OPTIONS]', result: { es: 'Cargar una imagen desde un archivo tar o STDIN', en: 'Load an image from a tar archive or STDIN' }, level: 1, nb: {} },
  { tech: 'docker', command: 'login', usage: 'docker login [OPTIONS] [SERVER]', result: { es: 'Iniciar sesión en un registro de Docker', en: 'Log in to a Docker registry' }, level: 1, nb: {} },
  { tech: 'docker', command: 'logout', usage: 'docker logout [OPTIONS] [SERVER]', result: { es: 'Cerrar sesión de un registro de Docker', en: 'Log out from a Docker registry' }, level: 1, nb: {} },
  { tech: 'docker', command: 'logs', usage: 'docker logs [OPTIONS] CONTAINER', result: { es: 'Obtener los registros de un contenedor', en: 'Fetch the logs of a container' }, level: 1, nb: {} },
  { tech: 'docker', command: 'pause', usage: 'docker pause CONTAINER [CONTAINER...]', result: { es: 'Pausar todos los procesos dentro de uno o más contenedores', en: 'Pause all processes within one or more containers' }, level: 1, nb: {} },
  { tech: 'docker', command: 'port', usage: 'docker port CONTAINER [PRIVATE_PORT[/PROTO]]', result: { es: 'Listar asignaciones de puerto o una asignación específica para el contenedor', en: 'List port mappings or a specific mapping for the container' }, level: 1, nb: {} },
  { tech: 'docker', command: 'ps', usage: 'docker ps [OPTIONS]', result: { es: 'Listar contenedores', en: 'List containers' }, level: 1, nb: {} },
  { tech: 'docker', command: 'pull', usage: 'docker pull [OPTIONS] NAME[:TAG|@DIGEST]', result: { es: 'Descargar una imagen o un repositorio de un registro', en: 'Pull an image or a repository from a registry' }, level: 1, nb: {} },
  { tech: 'docker', command: 'push', usage: 'docker push [OPTIONS] NAME[:TAG]', result: { es: 'Subir una imagen o un repositorio a un registro', en: 'Push an image or a repository to a registry' }, level: 1, nb: {} },
  { tech: 'docker', command: 'rename', usage: 'docker rename CONTAINER NEW_NAME', result: { es: 'Cambiar el nombre de un contenedor', en: 'Rename a container' }, level: 1, nb: {} },
  { tech: 'docker', command: 'restart', usage: 'docker restart [OPTIONS] CONTAINER [CONTAINER...]', result: { es: 'Reiniciar uno o más contenedores', en: 'Restart one or more containers' }, level: 1, nb: {} },
  { tech: 'docker', command: 'rm', usage: 'docker rm [OPTIONS] CONTAINER [CONTAINER...]', result: { es: 'Eliminar uno o más contenedores', en: 'Remove one or more containers' }, level: 1, nb: {} },
  { tech: 'docker', command: 'rmi', usage: 'docker rmi [OPTIONS] IMAGE [IMAGE...]', result: { es: 'Eliminar una o más imágenes', en: 'Remove one or more images' }, level: 1, nb: {} },
  { tech: 'docker', command: 'run', usage: 'docker run [OPTIONS] IMAGE [COMMAND] [ARG...]', result: { es: 'Ejecutar un comando en un nuevo contenedor', en: 'Run a command in a new container' }, level: 1, nb: {} },
  { tech: 'docker', command: 'save', usage: 'docker save [OPTIONS] IMAGE [IMAGE...]', result: { es: 'Guardar una o más imágenes en un archivo tar (transmitido a STDOUT de forma predeterminada)', en: 'Save one or more images to a tar archive (streamed to STDOUT by default)' }, level: 1, nb: {} },
  { tech: 'docker', command: 'search', usage: 'docker search [OPTIONS] TERM', result: { es: 'Buscar en Docker Hub imágenes', en: 'Search the Docker Hub for images' }, level: 1, nb: {} },
  { tech: 'docker', command: 'start', usage: 'docker start [OPTIONS] CONTAINER [CONTAINER...]', result: { es: 'Iniciar uno o más contenedores detenidos', en: 'Start one or more stopped containers' }, level: 1, nb: {} },
  { tech: 'docker', command: 'stats', usage: 'docker stats [OPTIONS] [CONTAINER...]', result: { es: 'Mostrar una transmisión en vivo de las estadísticas de uso de recursos del(los) contenedor(es)', en: 'Display a live stream of container(s) resource usage statistics' }, level: 1, nb: {} },
  { tech: 'docker', command: 'stop', usage: 'docker stop [OPTIONS] CONTAINER [CONTAINER...]', result: { es: 'Detener uno o más contenedores en ejecución', en: 'Stop one or more running containers' }, level: 1, nb: {} },
  { tech: 'docker', command: 'tag', usage: 'docker tag SOURCE_IMAGE[:TAG] TARGET_IMAGE[:TAG]', result: { es: 'Crear una etiqueta TARGET_IMAGE que se refiere a SOURCE_IMAGE', en: 'Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE' }, level: 1, nb: {} },
  { tech: 'docker', command: 'top', usage: 'docker top CONTAINER [ps OPTIONS]', result: { es: 'Mostrar los procesos en ejecución de un contenedor', en: 'Display the running processes of a container' }, level: 1, nb: {} },
  { tech: 'docker', command: 'unpause', usage: 'docker unpause CONTAINER [CONTAINER...]', result: { es: 'Reanudar todos los procesos dentro de uno o más contenedores', en: 'Unpause all processes within one or more containers' }, level: 1, nb: {} },
  { tech: 'docker', command: 'update', usage: 'docker update [OPTIONS] CONTAINER [CONTAINER...]', result: { es: 'Actualizar la configuración de uno o más contenedores', en: 'Update configuration of one or more containers' }, level: 1, nb: {} },
  { tech: 'docker', command: 'version', usage: 'docker version [OPTIONS]', result: { es: 'Mostrar la información de la versión de Docker', en: 'Show the Docker version information' }, level: 1, nb: {} },
  { tech: 'docker', command: 'wait', usage: 'docker wait CONTAINER [CONTAINER...]', result: { es: 'Bloquear hasta que uno o más contenedores se detengan, luego imprimir sus códigos de salida', en: 'Block until one or more containers stop, then print their exit codes' }, level: 1, nb: {} }
]
